name = "Microbenchmarks"
uuid = "d04c57ce-49d5-44bb-b39e-e10e2075fbb8"
authors = ["Viral B. Shah <ViralBShah@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "1"
